version: '2.0'
services:
  osin:
    build: osin/
    image: toan2/osin:1.8.6
    volumes:
      - ./data/:/data
      - ./.certs:/root/.certs:ro
      - ./osin/osin:/osin/osin:ro
    ports:
      - "5524:5524"
    environment:
      - PYTHONPATH=/osin
      - FLASK_ENV=development
    command: 
      - /bin/bash
      - -c
      - |
        poetry run python -m osin init -d /data
        # poetry run python -m osin start -d /data -p 5524 --certfile /root/.certs/fullchain.pem --keyfile /root/.certs/privkey.pem
        poetry run python -m osin start -d /data -p 5524 --wsgi
