[tool.poetry]
name = "osin"
version = "0.1.0"
description = "Rethink Experimenting"
authors = ["Binh Vu <binh@toan2.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.1"
rocksdb = "^0.7.0"
pandas = "^1.2.4"
streamlit = "^0.82.0"
python-dotenv = "^0.17.1"
peewee = "^3.14.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
